# Generated by Django 3.2.10 on 2023-12-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_property_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='media/property_images/%Y/%m/%d/')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, upload_to='media/property_images/%Y/%m/%d/')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='property_image_main',
            field=models.ImageField(upload_to='media/property_images/%Y/%m/%d/'),
        ),
    ]
